steps:
    - name: golang:1.20
      dir: 'api'
      entrypoint: /bin/bash
      args:
        - -c
        - |
            go get -t -d ./...

    # Docker api Build
    -   name: 'gcr.io/cloud-builders/docker'
        dir: 'api'
        args: [ 'build', '-t',
                'us-east1-docker.pkg.dev/personal-311605/personal/vue-golang-grpc-base/api:$SHORT_SHA', '.' ]

    # Docker push to Google Artifact Registry
    -   name: 'gcr.io/cloud-builders/docker'
        args: [ 'push', 'us-east1-docker.pkg.dev/personal-311605/personal/vue-golang-grpc-base/api:$SHORT_SHA' ]

    # yarn install
    -   name: 'gcr.io/cloud-builders/yarn'
        dir: 'view'
        args: [ 'install' ]

    # yarn build
    -   name: 'gcr.io/cloud-builders/yarn'
        dir: 'view'
        args: [ 'build' ]

    # Docker view Build
    -   name: 'gcr.io/cloud-builders/docker'
        dir: 'view'
        args: [ 'build', '-t',
                'us-east1-docker.pkg.dev/personal-311605/personal/vue-golang-grpc-base/view:$SHORT_SHA', '.' ]

    # Docker push view to Google Artifact Registry
    -   name: 'gcr.io/cloud-builders/docker'
        args: [ 'push', 'us-east1-docker.pkg.dev/personal-311605/personal/vue-golang-grpc-base/view:$SHORT_SHA' ]

    # Deploy api to GCP App Engine
    -   name: "gcr.io/cloud-builders/gcloud"
        dir: 'api'
        args:
          [
              "app",
              "deploy",
              "--image-url=us-east1-docker.pkg.dev/personal-311605/personal/vue-golang-grpc-base/api:$SHORT_SHA",
          ]
        timeout: "1600s"

    # Deploy view to GCP App Engine
    -   name: "gcr.io/cloud-builders/gcloud"
        dir: 'view'
        args:
          [
              "app",
              "deploy",
              "--image-url=us-east1-docker.pkg.dev/personal-311605/personal/vue-golang-grpc-base/view:$SHORT_SHA",
          ]
        timeout: "1600s"

images:
    - 'us-east1-docker.pkg.dev/personal-311605/personal/vue-golang-grpc-base/api:$SHORT_SHA'
    - 'us-east1-docker.pkg.dev/personal-311605/personal/vue-golang-grpc-base/view:$SHORT_SHA'
