version: '3.0'
services:
    api:
        build:
            context: ./api/docker
        ports:
            - "8082:8082"
            - "8080:8080"
    client:
        build:
            context: ./client
        ports:
            - "8080:8080"
            - "9000:9000"
