version: '3.0'
services:
    api:
        build:
            context: ./api
        ports:
            - "8082:8082" # gRPC
            - "8081:8081" # gRPC Gateway
    client:
        build:
            context: ./client
        environment:
            - API_HOST=localhost
            - NODE_ENV=development
        ports:
            - "80:8080"
