version: '3.0'
services:
    api:
        build:
            context: ./api
        ports:
            - "8082:8082" # gRPC
            - "8081:8081" # gRPC Gateway
        networks:
            - personal
    view:
        build:
            context: ./view
        environment:
            - API_HOST=api
            - NODE_ENV=production
        env_file:
            -   view/.env.local
        networks:
            - personal
        ports:
            - "80:8080"
networks:
    personal:
