version: '3.0'
services:
    api:
        build:
            context: ./api
        ports:
            - "8082:8082" # gRPC
            - "8081:8081" # gRPC Gateway
    client:
        build:
            context: ./client
        env_file:
            -   client/.env
        ports:
            - "8080:8080"
